package org.scalafin.convention

sealed abstract class Iso4217Currency(val fullName: String, val countries: List[Iso3166Country], val replacement: Option[Iso4217Currency] = None, val comments: Option[String] = None)
case object AFN extends Iso4217Currency("Afghani", List(AF))

case object ARA extends Iso4217Currency("Austral", List(AR))
case object THB extends Iso4217Currency("Baht", List(TH))
case object PAB extends Iso4217Currency("Balboa", List(PA))
case object ETB extends Iso4217Currency("Birr", List(ER, ET))
case object VEB extends Iso4217Currency("Bolivar", List(VE))
case object BOB extends Iso4217Currency("Boliviano", List(BO))
case object GHC extends Iso4217Currency("Cedi", List(GH))
case object CRC extends Iso4217Currency("Col—n (Costa Rican)", List(CR))
case object SVC extends Iso4217Currency("Col—n (El Salvadorian)", List(SV))
case object BAM extends Iso4217Currency("Convertible Mark", List(BA))
case object NIO extends Iso4217Currency("C—rdoba", List(NI))
case object BRL extends Iso4217Currency("Brazilian Real", List(BR))
case object BRR extends Iso4217Currency("Cruzeiro Real", List(BR), Some(BRL))
case object GMD extends Iso4217Currency("Dalasi", List(GM))
case object DZD extends Iso4217Currency("Dinar (Algerian)", List(DZ))
case object BHD extends Iso4217Currency("Dinar (Bahraini)", List(BH))
case object HRD extends Iso4217Currency("Dinar (Croatian)", List(HR))
case object IQD extends Iso4217Currency("Dinar (Iraqi)", List(IQ))
case object JOD extends Iso4217Currency("Dinar (Jordanian)", List(JO))
case object KWD extends Iso4217Currency("Dinar (Kuwaiti)", List(KW))
case object LYD extends Iso4217Currency("Dinar (Libyan)", List(LY))
case object MKD extends Iso4217Currency("Dinar (Macedonian)", List(MK))
case object CSD extends Iso4217Currency("Dinar (Serbian)", List(CS))
case object YER extends Iso4217Currency("Riyal (Yemeni)", List(YE))
case object YDD extends Iso4217Currency("Dinar (South Yemeni)", List(), Some(YER))
case object SDD extends Iso4217Currency("Dinar (Sudanese)", List(SD))
case object TND extends Iso4217Currency("Dinar (Tunisian)", List(TN))
case object MAD extends Iso4217Currency("Dirham (Moroccan)", List(MA, EH))
case object AED extends Iso4217Currency("Dirham (UAE)", List(AE))
case object STD extends Iso4217Currency("Dobra", List(ST))
case object AUD extends Iso4217Currency("Dollar (Australian)", List(AU, CX, CC, HM, KI, NR, NF, TV))
case object BSD extends Iso4217Currency("Dollar (Bahamian)", List(BS))
case object BBD extends Iso4217Currency("Dollar (Barbados)", List(BB))
case object BZD extends Iso4217Currency("Dollar (Belize)", List(BZ))
case object BMD extends Iso4217Currency("Dollar (Bermudian)", List(BM))
case object BND extends Iso4217Currency("Dollar (Brunei)", List(BN))
case object CAD extends Iso4217Currency("Dollar (Canadian)", List(CA))
case object KYD extends Iso4217Currency("Dollar (Cayman Islands)", List(KY))
case object XCD extends Iso4217Currency("Dollar (East Caribbean)", List(AI, AG, VG, DM, GD, MS, KN, LC, VC))
case object FJD extends Iso4217Currency("Dollar (Fiji)", List(FJ))
case object GYD extends Iso4217Currency("Dollar (Guyana)", List(GY))
case object HKD extends Iso4217Currency("Dollar (Hong Kong)", List(HK))
case object JMD extends Iso4217Currency("Dollar (Jamaican)", List(JM))
case object LRD extends Iso4217Currency("Dollar (Liberian)", List(LR))
case object MYR extends Iso4217Currency("Dollar (Malaysian)", List(MY), None, Some("Synonym Ringgit")) // Synonym Ringgit
case object NAD extends Iso4217Currency("Dollar (Namibian)", List(NA))
case object NZD extends Iso4217Currency("Dollar (New Zealand)", List(CK, NZ, NU, PN, TK))
case object SGD extends Iso4217Currency("Dollar (Singapore)", List(SG))
case object SBD extends Iso4217Currency("Dollar (Solomon Islands)", List(SB))
case object TWD extends Iso4217Currency("Dollar (Taiwan, New)", List(TW))
case object TTD extends Iso4217Currency("Dollar (Trinidad and Tobago)", List(TT))
case object ZWD extends Iso4217Currency("Dollar (Zimbabwe)", List(ZW))
case object VND extends Iso4217Currency("D™ng", List(VN))
case object GRD extends Iso4217Currency("Drachma", List(GR))
case object AMD extends Iso4217Currency("Dram", List(AM))
case object EUR extends Iso4217Currency("Euro", List(AT, BE, FI, FR, DE, GR, IE, IT, LU, NL, PT, ES, MC, VA, CS, SM, SI)) //  Also Serbian province of Kosovo and various FrenchÊdependencies.
case object XEU extends Iso4217Currency("ECU", List(), Some(EUR))
case object GQE extends Iso4217Currency("Ekwele", List(GQ))
case object CVE extends Iso4217Currency("Escudo (Caboverdiano)", List(CV))
case object PTE extends Iso4217Currency("Escudo (Portuguese)", List(PT), Some(EUR))
case object TPE extends Iso4217Currency("Escudo (Timorian)", List(), None, Some("Confirm country"))
case object FLORIN extends Iso4217Currency("Florin", List(), Some(EUR), Some("Find old ISO 4217 Code for Florin"))
case object HUF extends Iso4217Currency("Forint", List(HU))
case object BEF extends Iso4217Currency("Franc (Belgian)", List(BE), Some(EUR), Some("Synonym Frank"))
case object BEC extends Iso4217Currency("Franc (Belgian, Convertible)", List(BE), Some(EUR))
case object BEL extends Iso4217Currency("Franc (Belgian, Financial)", List(BE), Some(EUR))
case object BIF extends Iso4217Currency("Franc (Burundi)", List(BI))
case object KMF extends Iso4217Currency("Franc (Comorian)", List(KM))
case object XAF extends Iso4217Currency("Franc (de la CommunautŽ financi�re africaine [Central African Franc])", List(BJ, BF, CM, CF, TD, CG, CI, GQ, GA, GW, ML, NE, SN, TG))
case object XPF extends Iso4217Currency("Franc (des Comptoirs fran�ais du Pacifique [Pacific Franc])", List(PF, NC, WF))
case object DJF extends Iso4217Currency("Franc (Djibouti)", List(DJ))
case object FRF extends Iso4217Currency("Franc (French)", List(AD, FR, GF, TF, GP, MQ, YT, MC, RE, PM), Some(EUR))
case object GNS extends Iso4217Currency("Syli (Guinea)", List(GN))
case object GNF extends Iso4217Currency("Franc (Guinea)", List(GN), None, Some("Check which is valid, GNS or GNF, or if codes are true synonyms"))
case object LUF extends Iso4217Currency("Franc (Luxembourg)", List(LU), Some(EUR))
case object MGA extends Iso4217Currency("Ariary (Malagasy)", List(MG))
case object MGF extends Iso4217Currency("Franc (Malagasy)", List(MG), Some(MGA))
case object MLF extends Iso4217Currency("Franc (Malian)", List(ML))
case object RWF extends Iso4217Currency("Franc (Rwanda)", List(RW))
case object CHF extends Iso4217Currency("Franc (Swiss)", List(LI, CH))
case object XOF extends Iso4217Currency("Franc (West African)", List(NE, SN))
case object HTG extends Iso4217Currency("Gourde", List(HT))
case object PYG extends Iso4217Currency("Guarani", List(PY))
case object AWG extends Iso4217Currency("Guilder (Aruban)", List(AW))
case object NLG extends Iso4217Currency("Guilder (Dutch)", List(NL), Some(EUR), Some("Synonym Gulden"))
case object ANG extends Iso4217Currency("Guilder (Netherlands Antilles)", List(AN))
case object SRD extends Iso4217Currency("Dollar (Surinam)", List(SR))
case object SRG extends Iso4217Currency("Guilder (Surinam)", List(SR), Some(SRD))
case object UAH extends Iso4217Currency("Hryvna", List(UA))
case object PEI extends Iso4217Currency("Inti", List(PE))
case object UAK extends Iso4217Currency("Karbovanet", List(UA))
case object PGK extends Iso4217Currency("Kina", List(PG))
case object LAK extends Iso4217Currency("Kip", List(LA))
case object CZK extends Iso4217Currency("Koruna (Czech)", List(CZ))
case object CSK extends Iso4217Currency("Koruna (Czech)", List(CZ), Some(CZK), Some("Misuse"))
case object SKK extends Iso4217Currency("Koruna (Slovak)", List(SK))
case object ISK extends Iso4217Currency("Kr—na (Icelandic)", List(IS))
case object SEK extends Iso4217Currency("Krona (Swedish)", List(SE))
case object DKK extends Iso4217Currency("Krone (Danish)", List(DK, FO, GL))
case object NOK extends Iso4217Currency("Krone (Norwegian)", List(AQ, BV, NO, SJ))
case object EEK extends Iso4217Currency("Kroon", List(EE))
case object HRK extends Iso4217Currency("Kuna", List(HR))
case object MWK extends Iso4217Currency("Kwacha (Malawian)", List(MW))
case object ZMK extends Iso4217Currency("Kwacha (Zambian)", List(ZM))
case object MMK extends Iso4217Currency("Kyat", List(MM), None, Some("Formerly BUK"))
case object GEL extends Iso4217Currency("Lari", List(GE))
case object LVL extends Iso4217Currency("Lats", List(LA))
case object ALL extends Iso4217Currency("Lek", List(AL))
case object HNL extends Iso4217Currency("Lempira", List(HN))
case object SLL extends Iso4217Currency("Leone", List(SL))
case object MDL extends Iso4217Currency("Leu (Moldavian)", List(MD))
case object RON extends Iso4217Currency("Leu (New Romanian)", List(RO))
case object ROL extends Iso4217Currency("Leu (Romanian)", List(RO), Some(RON))
case object BGN extends Iso4217Currency("Lev", List(BG))
case object BGL extends Iso4217Currency("Lev", List(BG), Some(BGN))
case object SZL extends Iso4217Currency("Lilangeni", List(SZ))
case object ITL extends Iso4217Currency("Lira (Italian)", List(VA, IT, SM), Some(EUR))
case object MTL extends Iso4217Currency("Lira (Maltese)", List(MT))
case object TRY extends Iso4217Currency("Lira (New Turkish)", List(TR))
case object TRL extends Iso4217Currency("Lira (Turkish)", List(TR), Some(TRY))
case object LTL extends Iso4217Currency("Litas", List(LT))
case object LSL extends Iso4217Currency("Loti", List(LS))
case object LSM extends Iso4217Currency("Maloti", List(LS))
case object AZN extends Iso4217Currency("Manat (Azerbaijani)", List(AZ))
case object AZM extends Iso4217Currency("Manat (Azerbaijani)", List(AZ), None, Some("Check is true synonym"))
case object TMM extends Iso4217Currency("Manat (Turkmenistani)", List(TM))
case object DEM extends Iso4217Currency("Mark (Deutsche)", List(DE), Some(EUR), Some("Formerly DDM in east germany"))
case object FIM extends Iso4217Currency("Markka", List(FI), Some(EUR))
case object MZM extends Iso4217Currency("Metical", List(MZ))
case object NGN extends Iso4217Currency("Naira", List(NG))
case object ERN extends Iso4217Currency("Nakfa", List(ER))
case object AOA extends Iso4217Currency("Kwanza", List(AO), None, Some("Replaced AOK"))
case object MXN extends Iso4217Currency("New Peso (Mexican)", List(MX), None, Some("Replaced MXP"))
case object MXV extends Iso4217Currency("Mexican Unidad de Inversion", List(MX), None, Some("UDI Funds Code"))
case object UYU extends Iso4217Currency("New Peso (Uruguayan)", List(UY), None, Some("Replaced UYP"))
case object PEN extends Iso4217Currency("New Sol", List(PE), None, Some("Replaced PES"))
case object PLN extends Iso4217Currency("New Zloty", List(PL), None, Some("Replaced PLZ"))
case object BTN extends Iso4217Currency("Ngultrum", List(BT))
case object ARS extends Iso4217Currency("Nuevo Peso", List(AR), None, Some("Replaced ARP"))
case object MRO extends Iso4217Currency("Ouguiya", List(MR, EH))
case object TOP extends Iso4217Currency("Pa'anga", List(TO))
case object MOP extends Iso4217Currency("Pataca", List(MO))
case object ADP extends Iso4217Currency("Peseta (Andorran)", List(AD), Some(EUR))
case object ESP extends Iso4217Currency("Peseta (Spanish)", List(AD, ES, EH), Some(EUR))
case object BOP extends Iso4217Currency("Peso (Bolivian)", List(BO))
case object BOV extends Iso4217Currency("Mvdol (Bolivian)", List(BO), None, Some("Funds code"))
case object CLP extends Iso4217Currency("Peso (Chilean)", List(CL))
case object COP extends Iso4217Currency("Peso (Colombian)", List(CO))
case object COU extends Iso4217Currency("Unidad de Valor Real", List(CO), None, Some("Verify the correct/legacy Columbian currency"))
case object CUP extends Iso4217Currency("Peso (Cuban)", List(CU))
case object DOP extends Iso4217Currency("Peso (Dominican Republic)", List(DO))
case object GWP extends Iso4217Currency("Peso (Guinea-Bissau)", List(GW))
case object PHP extends Iso4217Currency("Peso (Philippines)", List(PH))
case object CYP extends Iso4217Currency("Pound (Cypriot)", List(CY))
case object EGP extends Iso4217Currency("Pound (Egytian)", List(EG))
case object FKP extends Iso4217Currency("Pound (Falkland)", List(FK))
case object GIP extends Iso4217Currency("Pound (Gibraltar)", List(GI))
case object LBP extends Iso4217Currency("Pound (Lebanese)", List(LB))
case object SHP extends Iso4217Currency("Pound (St Helena)", List(SH))
case object GBP extends Iso4217Currency("Pound (Sterling)", List(IO, VG, GS, GB))
case object SDP extends Iso4217Currency("Pound (Sudanese)", List(SD))
case object SYP extends Iso4217Currency("Pound (Syrian)", List(SY))
case object BWP extends Iso4217Currency("Pula", List(BW))
case object IEP extends Iso4217Currency("Punt", List(IE), Some(EUR))
case object GTQ extends Iso4217Currency("Quetzal", List(GT))
case object ZAR extends Iso4217Currency("Rand", List(LS, NA, ZA))
case object ZAL extends Iso4217Currency("Rand (financial)", List(ZA))
case object IRR extends Iso4217Currency("Rial (Iranian)", List(IR))
case object OMR extends Iso4217Currency("Rial (Omani)", List(OM))
case object KHR extends Iso4217Currency("Riel", List(KH))
case object QAR extends Iso4217Currency("Riyal (Qatari)", List(QA))
case object SAR extends Iso4217Currency("Riyal (Saudi)", List(SA))
case object BYR extends Iso4217Currency("Rouble (Belarussian)", List(BY))
case object RUB extends Iso4217Currency("Rouble (Russian Federation)", List(RU), None, Some("Formerly RUR"))
case object TJR extends Iso4217Currency("Rouble (Tajik)", List(TJ))
case object TJS extends Iso4217Currency("Somoni", List(TJ), None, Some("Check which is correct, TJR/TJS"))
case object MVR extends Iso4217Currency("Rufiyaa", List(MV))
case object INR extends Iso4217Currency("Rupee (Indian)", List(BT, IN))
case object MUR extends Iso4217Currency("Rupee (Mauritius)", List(MU))
case object NPR extends Iso4217Currency("Rupee (Nepalese)", List(NP))
case object PKR extends Iso4217Currency("Rupee (Pakistani)", List(PK))
case object SCR extends Iso4217Currency("Rupee (Seychelles)", List(IO, SC))
case object LKR extends Iso4217Currency("Rupee (Sri Lankan)", List(LK))
case object IDR extends Iso4217Currency("Rupiah", List(ID))
case object ATS extends Iso4217Currency("Schilling", List(AT), Some(EUR))
case object ILS extends Iso4217Currency("Shekel", List(IL))
case object KES extends Iso4217Currency("Shilling (Kenyan)", List(KE))
case object SOS extends Iso4217Currency("Shilling (Somali)", List(SO))
case object TZS extends Iso4217Currency("Shilling (Tanzanian)", List(TZ))
case object UGX extends Iso4217Currency("Shilling (Ugandan)", List(UG))
case object UGS extends Iso4217Currency("Shilling (Ugandan)", List(UG), Some(UGX))
case object KGS extends Iso4217Currency("Som (Kyrgyzstani)", List(KG))
case object UZS extends Iso4217Currency("Som (Uzbekistani)", List(UZ))
case object USD extends Iso4217Currency("US Dollar", List(AS, VG, EC, FM, GU, MH, PW, PA, PR, TC, US, UM, VI))
case object ECS extends Iso4217Currency("Sucre", List(EC), Some(USD))
case object BDT extends Iso4217Currency("Taka", List(BD))
case object WST extends Iso4217Currency("Tala", List(WS))
case object KZT extends Iso4217Currency("Tenge", List(KZ))
case object SIT extends Iso4217Currency("Tolar", List(SI), Some(EUR)) // Replaced by EUR 2006/10/30
case object MNT extends Iso4217Currency("Tugrik", List(MN))
case object CLF extends Iso4217Currency("Unidades de Fomento", List(CL))
case object VUV extends Iso4217Currency("Vatu", List(VU))
case object KPW extends Iso4217Currency("Won (North Korean)", List(KP))
case object KRW extends Iso4217Currency("Won (South Korean)", List(KR))
case object JPY extends Iso4217Currency("Yen", List(JP))
case object CNY extends Iso4217Currency("Yuan Renminbi", List(CN))
case object CDF extends Iso4217Currency("Franc (Congolaise)", List(CD))
case object CDZ extends Iso4217Currency("Zaire (New)", List(CD), Some(CDF), Some("Formerly ZRZ"))

// Precious metals
case object XPD extends Iso4217Currency("Palladium (one Troy ounce)", List())
case object XPT extends Iso4217Currency("Platinum (one Troy ounce)", List())
case object XAG extends Iso4217Currency("Silver (one Troy ounce)", List())
case object XAU extends Iso4217Currency("Gold (one Troy ounce)", List())

// Special EUA, EURCA and EMU units
case object XBA extends Iso4217Currency("European Composite Unit (EURCO) (Bonds market unit)", List())
case object XBB extends Iso4217Currency("European Monetary Unit (E.M.U.-6) (Bonds market unit)", List())
case object XBC extends Iso4217Currency("European Unit of Account 9 (E.U.A.-9) (Bonds market unit)", List())
case object XBD extends Iso4217Currency("European Unit of Account 17 (E.U.A.-17) (Bonds market unit)", List())
case object XDR extends Iso4217Currency("Special Drawing Rights (International Monetary Fund)", List())

// Special settlement currencies
case object XFO extends Iso4217Currency("Gold-franc (Special settlement currency)", List())
case object XFU extends Iso4217Currency("UIC franc (Special settlement currency)", List())